# root -l -q MisIDrate2D.cxx'("data_all", "/afs/cern.ch/work/s/ssindhu/private/qmisid_calc/all_cuts/2sigma_bw/", )' > /afs/cern.ch/work/s/ssindhu/private/qmisid_calc/all_cuts/2sigma_bw/misID_data_all_new.txt
# root -l -q MisIDrate2D.cxx'("data_all_2sigma", "/afs/cern.ch/work/s/ssindhu/private/qmisid_calc/new_bg/40_50_60/", "/eos/user/s/ssindhu/4tops/plots/QmisID/new_bg/40_50_60/")' > /afs/cern.ch/work/s/ssindhu/private/qmisid_calc/new_bg/40_50_60/misID_data_all_2sigma.txt
# root -l -q MisIDrate2D.cxx'("data_all_4sigma", "/afs/cern.ch/work/s/ssindhu/private/qmisid_calc/new_bins/40_50_60/", "/eos/user/s/ssindhu/4tops/plots/QmisID/new_bins/40_50_60/")' > /afs/cern.ch/work/s/ssindhu/private/qmisid_calc/new_bins/40_50_60/misID_data_all_4sigma.txt
# root -l -q MisIDrate2D.cxx'("data_all_5sigma", "/afs/cern.ch/work/s/ssindhu/private/qmisid_calc/new_bins/40_50_60/", "/eos/user/s/ssindhu/4tops/plots/QmisID/new_bins/40_50_60/")' > /afs/cern.ch/work/s/ssindhu/private/qmisid_calc/new_bins/40_50_60/misID_data_all_5sigma.txt
# root -l -q MisIDrate2D.cxx'("data_all", "/afs/cern.ch/work/s/ssindhu/private/qmisid_calc/new_bins/40_50_60/", "/eos/user/s/ssindhu/4tops/plots/QmisID/new_bins/40_50_60/")' > /afs/cern.ch/work/s/ssindhu/private/qmisid_calc/new_bins/40_50_60/misID_data_all_3sigma.txt
# root -l -q MisIDrate2D.cxx'("data_all", "/afs/cern.ch/work/s/ssindhu/private/qmisid_calc/test/")' > /afs/cern.ch/work/s/ssindhu/private/qmisid_calc/test/misID_data_all_new.txt
# root -l -q MisIDrate2D.cxx'("data_all", "/afs/cern.ch/work/s/ssindhu/private/qmisid_calc/all_cuts/3sigma_bw/")' > misID_data_all_test.txt
# root -l -q MisIDrate2D5bins.cxx'("data_all_2sigma", "/afs/cern.ch/work/s/ssindhu/private/qmisid_calc/new_bins/45_60_90_130/", "/eos/user/s/ssindhu/4tops/plots/QmisID/45_60_90_130/")' > /afs/cern.ch/work/s/ssindhu/private/qmisid_calc/new_bins/45_60_90_130/misID_data_all_2sigma.txt
# root -l -q MisIDrate2D5bins.cxx'("data_all_4sigma", "/afs/cern.ch/work/s/ssindhu/private/qmisid_calc/new_bg/40_60_90_130/", "/eos/user/s/ssindhu/4tops/plots/QmisID/40_60_90_130/")' > /afs/cern.ch/work/s/ssindhu/private/qmisid_calc/new_bg/40_60_90_130/misID_data_all_4sigma.txt
# root -l -q MisIDrate2D5bins.cxx'("data_all_3sigma", "/afs/cern.ch/work/s/ssindhu/private/qmisid_calc/new_bg/40_60_90_130/", "/eos/user/s/ssindhu/4tops/plots/QmisID/40_60_90_130/")' > /afs/cern.ch/work/s/ssindhu/private/qmisid_calc/new_bg/40_60_90_130/misID_data_all_3sigma.txt
# root -l -q MisIDrate2D5bins.cxx'("data_all_5sigma", "/afs/cern.ch/work/s/ssindhu/private/qmisid_calc/new_bg/40_60_90_130/", "/eos/user/s/ssindhu/4tops/plots/QmisID/40_60_90_130/")' > /afs/cern.ch/work/s/ssindhu/private/qmisid_calc/new_bg/40_60_90_130/misID_data_all_5sigma.txt
# root -l -q MisIDrate2D3bins.cxx'("data_all_4sigma", "/afs/cern.ch/work/s/ssindhu/private/qmisid_calc/new_bins/60_130/CO/", "/eos/user/s/ssindhu/4tops/plots/QmisID/60_130/CO/")' > /afs/cern.ch/work/s/ssindhu/private/qmisid_calc/new_bins/60_130/CO/misID_data_all_4sigma.txt
# root -l -q MisIDrate2D3bins.cxx'("data_all", "/afs/cern.ch/work/s/ssindhu/private/qmisid_calc/new_bins/60_130/CO/", "/eos/user/s/ssindhu/4tops/plots/QmisID/60_130/CO/")' > /afs/cern.ch/work/s/ssindhu/private/qmisid_calc/new_bins/60_130/CO/misID_data_all_3sigma.txt
# root -l -q MisIDrate2D3bins.cxx'("data_all_5sigma", "/afs/cern.ch/work/s/ssindhu/private/qmisid_calc/new_bins/60_130/CO/", "/eos/user/s/ssindhu/4tops/plots/QmisID/60_130/CO/")' > /afs/cern.ch/work/s/ssindhu/private/qmisid_calc/new_bins/60_130/CO/misID_data_all_5sigma.txt
root -l -q MisIDrate2D3binseta0.cxx'("data_all_4sigma", "/afs/cern.ch/work/s/ssindhu/private/qmisid_calc/etabins12/60_90/gammastr0/", "/eos/user/s/ssindhu/4tops/plots/QmisID/60_90/gammastr0/")' > /afs/cern.ch/work/s/ssindhu/private/qmisid_calc/etabins12/60_90/gammastr0/misID_data_all_4sigma.txt
root -l -q MisIDrate2D3binseta0.cxx'("data_all_3sigma", "/afs/cern.ch/work/s/ssindhu/private/qmisid_calc/etabins12/60_90/gammastr0/", "/eos/user/s/ssindhu/4tops/plots/QmisID/60_90/gammastr0/")' > /afs/cern.ch/work/s/ssindhu/private/qmisid_calc/etabins12/60_90/gammastr0/misID_data_all_3sigma.txt
root -l -q MisIDrate2D3binseta0.cxx'("data_all_5sigma", "/afs/cern.ch/work/s/ssindhu/private/qmisid_calc/etabins12/60_90/gammastr0/", "/eos/user/s/ssindhu/4tops/plots/QmisID/60_90/gammastr0/")' > /afs/cern.ch/work/s/ssindhu/private/qmisid_calc/etabins12/60_90/gammastr0/misID_data_all_5sigma.txt
